idp:
  host: "idp-rt.us-east-1.stgx.anypoint.mulesoft.com"
  accessTokenUrl: "https://stgx.anypoint.mulesoft.com/accounts/api/v2/oauth2/token"
  clientId: "c0da0c7f23124108ae7da6e47aaf9a2e"
  clientSecret: "47728601379F42b486A366D550A74755"
  actionId: "0e4b4285-99d7-4b14-94ce-58bf5a75f0ec"
  actionVersion: "1.2.0"

mulesoft:
  orgId: "c6cabd5c-742d-44d0-84b7-9e5b861e0da9"
  pollingFrequency: "30"
  
http:
  port: "8081"